//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cygshopnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registeration
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public decimal phonenumber { get; set; }
        public int isadmin { get; set; }
    
        public virtual user_cart user_cart { get; set; }
    }
}
